# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /data/UE521
GAMEPROJECTFILE =/home/lkhpc/CarlaUE5/CarlaUE5.uproject

TARGETS = \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame \
	CarlaUE5-Linux-DebugGame  \
	CarlaUE5-Linux-Shipping  \
	CarlaUE5 \
	CarlaUE5Editor-Linux-DebugGame  \
	CarlaUE5Editor-Linux-Shipping  \
	CarlaUE5Editor\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend CarlaUE5Editor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug CarlaUE5Editor-Linux-Debug


UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

CarlaUE5-Linux-DebugGame:
	 $(PROJECTBUILD) CarlaUE5 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

CarlaUE5-Linux-Shipping:
	 $(PROJECTBUILD) CarlaUE5 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

CarlaUE5:
	 $(PROJECTBUILD) CarlaUE5 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

CarlaUE5Editor-Linux-DebugGame:
	 $(PROJECTBUILD) CarlaUE5Editor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

CarlaUE5Editor-Linux-Shipping:
	 $(PROJECTBUILD) CarlaUE5Editor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

CarlaUE5Editor:
	 $(PROJECTBUILD) CarlaUE5Editor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
